### ISSUE TITLE
Removing command-line arguments

### ISSUE THREAD

**Issue by moderatorman** [thomdixon/SaltwaterTaffy#4]
Right, so I'm doing a scan, using the following code:
```
var target = new Target(hostname);
var result = new Scanner(target).PortScan(ScanType.Syn);
```
I hadn't set any PersistentOptions so I had assumed this would only have 1 or 2 command-line arguments, but it has 4, not including the one for XML output: `-sV -O -sS -sU`
My goal here is this: `-p 1-65535 -T4 -A -v`
So, I tried the following:
```
var target = new Target(hostname);
var scanner = new Scanner(target);
scanner.PersistentOptions = new NmapOptions
{
	NmapFlag.A,
	NmapFlag.AggressiveTiming,
	NmapFlag.Verbose,
	{ NmapFlag.PortSpecification, "1-65535" }
};
var result = scanner.PortScan();
```
That added all the flags I wanted, but still had the arguments that I didn't specify. Any tips on how to remove those?

**Comment by thomdixon** [comment]
Writing this on a phone, so sorry for the formatting.

Yeah, the `PortScan` convenience method always tries to do OS and service version detection: https://github.com/thomdixon/SaltwaterTaffy/blob/321228baece2a2a770044196f0fbc43b40599fb2/SaltwaterTaffy/Scanner.cs#L282

What you want is something like:

```csharp
var ctx = new NmapContext
{
    Target = target.ToString(),
    WindowStyle = ProcessWindowStyle.Hidden
};

var options = new NmapOptions
{
	NmapFlag.A,
	NmapFlag.AggressiveTiming,
	NmapFlag.Verbose,
	{ NmapFlag.PortSpecification, "1-65535" }
};

ctx.Options.AddAll(options);

var result = new ScanResult(ctx.Run());
```

Does that help?

**Comment by moderatorman** [comment]
That worked perfectly. Thank you. Sorry for the late reply.

Your library is really great by the way.
