### ISSUE TITLE
Path to nmap is invalid

### ISSUE THREAD

**Issue by gsakel1** [thomdixon/SaltwaterTaffy#7]
I change the path to "C:\Program Files (x86)\Nmap" but keep getting this error. Please help

**Comment by thomdixon** [comment]
> I change the path to "C:\Program Files (x86)\Nmap" but keep getting this error. Please help

Do you mean you set the `Path` property to that? If so, the `Path` must be the full path to the `nmap.exe`. 

You can also ensure that `C:\Program Files (x86)\Nmap` is in your `PATH` environment variable and the library should find it automatically.

**Comment by gsakel1** [comment]
In the Windows environment variables, "C:\Program Files (x86)\Nmap" is in there already. When I debug the program it stops at the "Path to nmap is invalid" and will allow me to put in a value for Path inside of visual studio, but still won't work

**Comment by thomdixon** [comment]
This means that either the string is empty (unlikely if you're setting it in VS), or `File.Exists(Path)` is returning `false`. You ensured that `Path` is set to the full path to the executable? e.g., `C:\Program Files (x86)\Nmap\nmap.exe` (or whatever the full path to `nmap.exe` is?)

**Comment by gsakel1** [comment]
Just got it, I added the path in my system environment variables instead of user variables. Seems like it's working now
